### ISSUE TITLE
config import fails

### ISSUE THREAD

**Issue by Morgy93** [redchamps/clean-admin-menu#15]
Hello,

getting the following error upon config import:
```
$ magento app:config:import
Processing configurations data from configuration file...
Import failed: Class RedChamps\CleanMenu\Model\Config\Backend\Modules does not exist
```

The class `RedChamps\CleanMenu\Model\Config\Backend\Modules` really doesn't exist, but why does it ask for it?

Any idea?

**Comment by rav-redchamps** [comment]
This class is virtual type in file https://github.com/redchamps/clean-admin-menu/blob/master/etc/adminhtml/di.xml

**Comment by rav-redchamps** [comment]
@Morgy93 Also, couldn't repeat it on Magento Opensource 2.3.5-p1 using the command 

magento app:config:import

is there a specific scenario or Magento edition to repeat it?

**Comment by Morgy93** [comment]
Using 2.3.5-p1 as well.

Try to do `magento app:config:dump` first and `magento app:config:import` afterwards.
Fails for me all the time with the same error.

**Comment by rav-redchamps** [comment]
Just tried it. the dump command works well but import command returns message

Nothing to import

instead of an error

**Comment by Morgy93** [comment]
I tried it on two different M2 2.3.5-p1 with the same error, but that doesn't mean that it could be caused by something else they both share.

Maybe you could try to dump data, change some setting in config.php (for example disable or enable some shipping method) and then import again.

**Comment by rav-redchamps** [comment]
Perfect! I am able to repeat it and evaluating reason & fix.

**Comment by rav-redchamps** [comment]
Manual fix is, replace below code in file etc/adminhtml/di.xml

```
<virtualType name="RedChamps\CleanMenu\Model\Config\Backend\Modules" type="RedChamps\CleanMenu\Model\Config\Backend\Cache">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="cache_tags" xsi:type="array">
                    <item name="admin_menu" xsi:type="const">Magento\Backend\Block\Menu::CACHE_TAGS</item>
                </item>
            </argument>
        </arguments>
    </virtualType>
```

with

```
<type name="RedChamps\CleanMenu\Model\Config\Backend\Cache">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="cache_tags" xsi:type="array">
                    <item name="admin_menu" xsi:type="const">Magento\Backend\Block\Menu::CACHE_TAGS</item>
                </item>
            </argument>
        </arguments>
    </type>

```

and replace all the occurrences of text

`RedChamps\CleanMenu\Model\Config\Backend\Modules`

with

`RedChamps\CleanMenu\Model\Config\Backend\Cache`

in file etc/adminhtml/system.xml

We will make a new release within a few days with this fix.

**Comment by thomas-kl1** [comment]
Hi

Did you try to move

```xml
<virtualType name="RedChamps\CleanMenu\Model\Config\Backend\Modules" type="RedChamps\CleanMenu\Model\Config\Backend\Cache">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="cache_tags" xsi:type="array">
                    <item name="admin_menu" xsi:type="const">Magento\Backend\Block\Menu::CACHE_TAGS</item>
                </item>
            </argument>
        </arguments>
    </virtualType>
```

to global di.xml? (etc/di.xml in the module)

**Comment by rav-redchamps** [comment]
@thomas-kl1 I haven't tried it. But possibly that will fix it as this seems to be the root cause.

But what's the reason for having the virtual class type in the first place? when we can directly specify arguments to the original class like below

```
<type name="RedChamps\CleanMenu\Model\Config\Backend\Cache">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="cache_tags" xsi:type="array">
                    <item name="admin_menu" xsi:type="const">Magento\Backend\Block\Menu::CACHE_TAGS</item>
                </item>
            </argument>
        </arguments>
    </type>
```

**Comment by thomas-kl1** [comment]
`\RedChamps\CleanMenu\Model\Config\Backend\Cache` is generic and so its naming. It allows to reuse the class for multiple purposes, we keep in mind in the future new cache tags can be deployed to handle the system structures. It's more defensive design.

**Comment by rav-redchamps** [comment]
Got it. Thanks for explaining.

**Comment by Morgy93** [comment]
Well, I can at least confirm that #16 fixes the issue, thanks!

We just need a new release now. 🙂 Still closing it already~

**Comment by rav-redchamps** [comment]
@Morgy93 Thanks for confirming that the issue is resolved. 

We are aware that the new release is pending. Actually, we are working on some more fixes/improvements & willing to include all of them in the next release.

It will be out soon.
