### ISSUE TITLE
Accessing extensions requires new permissions after install

### ISSUE THREAD

**Issue by scottsb** [redchamps/clean-admin-menu#17]
Any users set up with limited privileges who had been granted access to certain third-party extensions will initially no longer be able to access those once this module is installed, because they need to be granted access to the "Extensions" ACL resource that this module adds.

Ideally this would not be necessary, with the module's normal permissions taking effect without change, but at a minimum this should be documented in the setup instructions.

**Comment by rav-redchamps** [comment]
@scottsb Thanks for reporting this. Will take care of it in upcoming release which should be out during second half of current month.

**Comment by rav-redchamps** [comment]
Hi @scottsb 

This issue has been fixed in recently released version 1.0.8.

Closing this issue for now. Please feel free to reopen if you still found it unsolved.
