### ISSUE TITLE
"Powered by" labels

### ISSUE THREAD

**Issue by scottsb** [redchamps/clean-admin-menu#19]
I would request that you reconsider the "powered by Redchamps" links that you have added to this module in a recent version. While I understand and appreciate that you're putting your time into maintaining this as an open source product, which you have no obligation to do, including these links directly violates the whole purpose of this module: which is to clean up the Magento admin. Yes, the links are less intrusive than vendors sticking their logos all over the place, but for us, it still undermines the reason we had begun installing this for clients (sufficiently so we may stop using it).

It is of course your right to leave these in, and I absolutely understand the motivation, but I do hope you will change your mind.

**Comment by rav-redchamps** [comment]
Hi @scottsb 

I understand your point & we are discussing this internally. I will get a final update/confirmation on this within current week.

**Comment by rav-redchamps** [comment]
Hi @scottsb 

Just want to share an update here, this is taking more time than the usual due high workload we are having at the moment. But be assured that we haven't forgot about it. This will still take some time approximately 15 days from now but we will get back with some positive outcome for sure :-)

**Comment by rav-redchamps** [comment]
Hey @scottsb 

Sorry again for the delay.

Unfortunately, we couldn't made up our mind to disable the powered by links completely as of now. However, in the latest release, we have added a extension setting to disable them. Below command is shortcut for that

php bin/magento config:set clean_admin_menu/settings/promo 0

I know this is just extra workaround & not a ideal resolution. But I hope this helps, till the time we remove them completely.

**Comment by rav-redchamps** [comment]
Hi @scottsb 

I have a good news for you. The powered by links will be removed in next version, hopefully will be released by the end of this month.

**Comment by rav-redchamps** [comment]
@scottsb Powered by links has been removed in version 1.1.5 (released few minutes ago). Sorry for acting late on this &  thanks again for your feedback.
