### ISSUE TITLE
Submenu is not rendering correctly

### ISSUE THREAD

**Issue by czettnersandor** [redchamps/clean-admin-menu#20]
I noticed in two different installations that the menu is not breaking up into submenus. See screenshot of the correct menu:
![image](https://user-images.githubusercontent.com/263174/126295336-8e9806c0-42e1-4cf9-a5c0-44c916b07b7d.png)
And on the other installation, it looks like this:
![image](https://user-images.githubusercontent.com/263174/126295516-479698eb-d540-4acb-8c01-84488486f00e.png)
The difference in the html is that the first menu has level-0 class, where on the second screenshot, the same menu is level-1.
The first one is Magento 2.3.6, the second one is 2.4.2

**Comment by rav-redchamps** [comment]
Hi @czettnersandor 

Thanks for reporting it.

Somehow this is happens for installation running over PHP 7.4. I am checking it & get back to you soon.

**Comment by rav-redchamps** [comment]
@czettnersandor This has been fixed & new release 1.1.1 has been made. Please update the extension & feel free to let me know if you still see any problem.
