### ISSUE TITLE
2.4 compatibility 

### ISSUE THREAD

**Issue by onlinebizsoft** [redchamps/clean-admin-menu#21]
Do you still maintain this? It would be great if you make this working with latest Magento release 2.4.3

**Comment by rav-redchamps** [comment]
@onlinebizsoft yes, we do maintain it & as per our tests it work on 2.4.3. May you please share the specific problem you're facing on 2.4.3

**Comment by rav-redchamps** [comment]
Hey @onlinebizsoft 

Closing this issue in the absence of your response. Please feel free to reopen it with your comment.
