### ISSUE TITLE
Magefan succeeded to add their own entry

### ISSUE THREAD

**Issue by thomas-kl1** [redchamps/clean-admin-menu#22]
![Screenshot from 2021-09-27 14-54-33](https://user-images.githubusercontent.com/20971693/134912236-c0f8baa9-110b-47f5-973d-880ee23a2139.png)

**Comment by thomas-kl1** [comment]
I'll work on it later :) unless you already have a fix

**Comment by rav-redchamps** [comment]
Hey @thomas-kl1 

Thanks for reporting this.

Possibly they add this menu item via plugin or observer instead of menu.xml.

In case you didn’t get a chance to look at this, I will be fixing this by tomorrow.

**Comment by rav-redchamps** [comment]
Just pushed a fix https://github.com/redchamps/clean-admin-menu/commit/2e6abb45c436f96e95598ea4bc014adcb1e74fc9 not sure if it's optimal. 

Please give it a look and see if you can suggest changes.

**Comment by thomas-kl1** [comment]
thanks @rav-redchamps for the fix! Nice to see it will also prevents any third party vendors to add menu entry with this method
