### ISSUE TITLE
Exception #0 (Exception): Notice: Undefined index:  in vendor/redchamps/module-clean-admin-menu/Model/RuleFactory.php on line 35

### ISSUE THREAD

**Issue by mcspronko** [redchamps/clean-admin-menu#24]
Environment: Magento Open Source 2.3.5-p2
PHP 7.3.28
MAGE_MODE: developer

Steps to reproduce:
* install the extension via composer package manager
* run the `bin/magento setup:upgrade` command
* Open Magento Admin and observe the result

Actual result:
* An error occurred on the page
`Exception #0 (Exception): Notice: Undefined index:  in vendor/redchamps/module-clean-admin-menu/Model/RuleFactory.php on line 35`

Expected result:
* Magento Admin has been successfully loaded without errors.

**Comment by mcspronko** [comment]
Here is my local patch for this issue that worked for me. I am not sure which one of the 2 rules should be used by default.

```php
diff --git a/vendor/redchamps/module-clean-admin-menu/Model/RuleFactory.php b/vendor/redchamps/module-clean-admin-menu/Model/RuleFactory.php
index eec15918..c01438a6 100644
--- a/vendor/redchamps/module-clean-admin-menu/Model/RuleFactory.php
+++ b/vendor/redchamps/module-clean-admin-menu/Model/RuleFactory.php
@@ -32,6 +32,6 @@ final class RuleFactory
 
     public function create(string $ruleId, array $arguments): IsAllowedInterface
     {
-        return $this->objectManager->create($this->rules[$ruleId], $arguments);
+        return $this->objectManager->create($this->rules[$ruleId] ?? $this->rules['allowedByDefault'], $arguments);
     }
 }

```

**Comment by rav-redchamps** [comment]
Hey @mcspronko 

The rules param is defined here https://github.com/redchamps/clean-admin-menu/blob/17892ce3f16da5dac061205878541aa5ab3202d4/etc/adminhtml/di.xml#L80  

This isn't being read in your case due to Magento cache. Please revert the code change and run bin/magento c:f that should solve it.

Kindly confirm if this solves the problem.

**Comment by mcspronko** [comment]
@rav-redchamps thanks for the reply.
After the `setup:upgrade` I did have a clean cache directory. The `$ruleId` argument was NULL in that case, that is the reason for the exception.

**Comment by rav-redchamps** [comment]
That's bit odd. The ruleId should be read from here https://github.com/redchamps/clean-admin-menu/blob/17892ce3f16da5dac061205878541aa5ab3202d4/etc/config.xml#L13 through file https://github.com/redchamps/clean-admin-menu/blob/17892ce3f16da5dac061205878541aa5ab3202d4/Model/RuleConfig.php#L47

It seems like connected to some of the Magento or external cache but I will be checking this further & get back to you by tomorrow.

**Comment by mcspronko** [comment]
I cleaned the cache and tried everything from scratch, everything seems fine now. Closing the ticket. Thanks for the feedback and fast response.
