### ISSUE TITLE
2.4.4 (PHP 8.1) compatibility

### ISSUE THREAD

**Issue by rav-redchamps** [redchamps/clean-admin-menu#26]
Extension will produce below error in the 2.4.4 (PHP 8.1) admin panel 

Error: Call to undefined method ReflectionUnionType::getName() in /m2/244/vendor/magento/framework/Code/Generator/EntityAbstract.php:335

This is being caused by Magento 2.4.4 core issue reported here https://github.com/magento/magento2/issues/35292 and we are looking for some temporary fix till the time the core issue gets resolved.

**Comment by HRR1337** [comment]
I so hope this will be fixed soon by Magento!

**Comment by Yonn-Trimoreau** [comment]
Apparently they got it fixed in 2.4.5

**Comment by lfolco** [comment]
If you need a patch, they posted it in the original issue here: https://github.com/magento/magento2/issues/35292#issuecomment-1251876930
