### ISSUE TITLE
Can't uninstall this module. Help please.

### ISSUE THREAD

**Issue by mkutev** [redchamps/clean-admin-menu#27]
I need to uninstall this module.
I've tried `bin/magento module:uninstall --clear-static-content --remove-data` as well as `bin/magento module:disable RedChamps_CleanMenu` followed by `composer remove redchamps/module-clean-admin-menu`. 
Both commands successfully execute and after running `setup:upgrade` and clearing cache, I'm left with the following error when I try to load any page on the website:

`1 exception(s):
Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/var/www/html/vendor/redchamps/module-clean-admin-menu/etc/module.xml" file can't be read. Warning!file_get_contents(/var/www/html/vendor/redchamps/module-clean-admin-menu/etc/module.xml): failed to open stream: No such file or directory
Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/var/www/html/vendor/redchamps/module-clean-admin-menu/etc/module.xml" file can't be read. Warning!file_get_contents(/var/www/html/vendor/redchamps/module-clean-admin-menu/etc/module.xml): failed to open stream: No such file or directory
#1 Magento\Framework\Module\ModuleList\Loader->getModuleConfigs() called at [vendor/magento/framework/Module/ModuleList/Loader.php:83]
#2 Magento\Framework\Module\ModuleList\Loader->load() called at [vendor/magento/framework/Module/ModuleList.php:72]
#3 Magento\Framework\Module\ModuleList->getAll() called at [vendor/magento/framework/Module/ModuleList.php:91]
#4 Magento\Framework\Module\ModuleList->getOne() called at [vendor/magento/framework/Module/DbVersionInfo.php:144]
#5 Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual() called at [vendor/magento/framework/Module/DbVersionInfo.php:59]
#6 Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate() called at [vendor/magento/framework/Module/DbVersionInfo.php:103]
#7 Magento\Framework\Module\DbVersionInfo->getDbVersionErrors() called at [vendor/magento/framework/Module/Plugin/DbStatusValidator.php:119]
#8 Magento\Framework\Module\Plugin\DbStatusValidator->getGroupedDbVersionErrors() called at [vendor/magento/framework/Module/Plugin/DbStatusValidator.php:53]
#9 Magento\Framework\Module\Plugin\DbStatusValidator->beforeDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:121]
#10 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/amasty/aminvisiblecaptcha/Plugin/Framework/App/FrontControllerInterface/ValidateCaptcha.php:118]
#11 Amasty\InvisibleCaptcha\Plugin\Framework\App\FrontControllerInterface\ValidateCaptcha->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#12 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:75]
#13 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#14 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#15 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#16 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#17 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#18 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#19 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]`

Please help me. I don't understand why Magento is still looking for this module....
I double checked the `setup_module` table, composer.json, and composer.lock files, and the module isn't mentioned anywhere in them.

Thanks in advance.

**Comment by rav-redchamps** [comment]
Seems like you’re having additional cache. Possibly it should be opcode cache.

Please try flushing it.

If that isn’t case the look for other caches like redis, varnish etc

**Comment by mkutev** [comment]
Is it ok to just restart php? I'm not sure how to flush opcache.
Thanks for fast reply!

**Comment by rav-redchamps** [comment]
Yes, you can or follow below article to flush it

https://serverguy.com/magento/flush-php-opcache/

**Comment by mkutev** [comment]
@rav-redchamps Thank you so much, that worked! 
I learned something new.
Cheers

**Comment by mkutev** [comment]
@rav-redchamps Sorry to bug you again but I have a general question.
Sometimes when I install a module, I run `setup:upgrade` and then `setup:di:compile` , but even after that, the website throws an error such as `1 exception(s):
Exception #0 (InvalidArgumentException): Plugin class Swissup\Core\Plugin\StoreSwitcherBlock doesn't exist`

What do I need to do to make sure all of the classes are generating properly?
Thanks again
