### ISSUE TITLE
No parent items results in an empty menu item

### ISSUE THREAD

**Issue by refueledinc** [redchamps/clean-admin-menu#3]
If the admin main menu does not have any items to clean up, the `Extensions` menu item still shows in the menu and does not open.

It would be nice if the `Extensions` item did not show when there are no parent items to group, while still cleaning up the `Configuration` menu items.

**Comment by rav-redchamps** [comment]
@refueledinc Thanks for the feedback and I agree that it should behave as you described.

We are planning the next release tomorrow & will include this change.

**Comment by rav-redchamps** [comment]
@refueledinc This has been fixed in newly released version 1.0.3
