### ISSUE TITLE
Sort alphabetically

### ISSUE THREAD

**Issue by vseager** [redchamps/clean-admin-menu#30]
A nice addition to this would be to alphabetically sort the third-party extensions with the "Extensions" tabs in `Stores > Configuration`.

**Comment by rav-redchamps** [comment]
Hey @vseager 

Nice suggestion. Are you expecting the alphabetical sort of only vendor names or their extension names as well?

**Comment by rav-redchamps** [comment]
Just published version **1.1.4** that sorts both vendor names (tabs) & their extension names (sections) alphabetically.

Please update the extension & feel free to let me know here if you see any problem.
