### ISSUE TITLE
Extension not working with FME Extension menu 

### ISSUE THREAD

**Issue by abdokouta** [redchamps/clean-admin-menu#32]
Issue Description:
The plugin is intended to work with different modules, including the FME extension. However, there is an issue where the FME extension menu item is not correctly setting in the Extension menu. Instead, it still has its own menu item, as shown in the attached screenshot.

Steps to Reproduce:

Install the plugin and the FME extension.
Navigate to the Extension menu in the admin panel.
Expected Behavior:
The FME extension menu item should be integrated into the Extension menu, providing a unified menu structure for all modules.

Actual Behavior:
The FME extension menu item remains separate from the Extension menu, causing a disjointed menu structure.

Screenshot:
<img width="1800" alt="Screen Shot 2024-02-20 at 7 01 24 PM" src="https://github.com/redchamps/clean-admin-menu/assets/12934929/6f494c0a-e1f1-4744-9ee1-06c5502cdcb0">

**Comment by rav-redchamps** [comment]
Hi @abdokouta 

I have tried replicating this on Magento 2.4.6-3 with FME's one of free extension https://www.fmeextensions.com/request-for-quote-magento-2 & the menu got successfully moved to extensions menu item. Please see below screenshot for the reference. 

Possibly, the extension you're using from FME is adding menu item differently then doing it via menu.xml file. As, that's paid extension & I don't have access to it, in this case may you please check their code & share info about how they're adding the menu item. I will try to debug it from that info.

<img width="1467" alt="Screenshot 2024-02-21 at 4 22 58 PM" src="https://github.com/redchamps/clean-admin-menu/assets/5336201/f190b438-c4d3-492e-ad3f-ed947f0b4781">

**Comment by rav-redchamps** [comment]
Hi @abdokouta 

Closing the issue in the absence of your response. Please feel free to reopen it in the future with more details.
