### ISSUE TITLE
Move Find partners & extensions to bottom of Extensions tab

### ISSUE THREAD

**Issue by paales** [redchamps/clean-admin-menu#4]

**Comment by rav-redchamps** [comment]
Hi @paales 

Thank you for your feedback. What I understood is you want to move "partners & extensions" menu item under "Extensions" menu item

May you please share any specific reason for this request. In our opinion, this is Magento's native item and should be on the main menu. But if you have a strong opinion that it should be moved then we are happy to relocate it :-)

**Comment by rav-redchamps** [comment]
Hi @paales 

Unfortunately, we have to close this issue as we haven't heard back from you. But please feel to reopen if you have further input.

**Comment by paales** [comment]
@rav-redchamps Sorry for my delayed response. Wasn't my intention to make a 'fire-and-forget' issue. 

The reason is to clean up the Admin Panel. I think I've never actually pressed on the button intentionally and it would be great if it could be cleaned up some more. I think it would fit in the goal of this module: Clean up the Admin Panel.

I think we're going to install it on every shop we're running :)

**Comment by rav-redchamps** [comment]
@paales Make sense and good to hear that you will be using it in all of your shops. 

We will make this change part of the upcoming release. Also, we have started a poll here https://twitter.com/_redChamps/status/1222509007010549761 in order to gather more opinions about it.

**Comment by rav-redchamps** [comment]
@paales This has been implemented in recent release 1.0.3. Closing this issue.

**Comment by paales** [comment]
Very nice! Will check it out :)
