### ISSUE TITLE
Compatibility with ElasticSuite

### ISSUE THREAD

**Issue by refueledinc** [redchamps/clean-admin-menu#5]
There seems to be a compatibility issue with ElasticSuite menu items.

1. Please install https://github.com/Smile-SA/elasticsuite
2. Go to Extensions > ElasticSuite > Search Engine > Search Relevance
3. Menu item will redirect to dashboard with `Invalid security or form key. Please refresh the page.`
4. The route is `smile_elasticsuite/search_request_relevanceconfig/index/`

**Comment by rav-redchamps** [comment]
@refueledinc we are able to repeat it and will resolve it soon. In case, you would like to submit a pull request for this, please feel to do that :-)

**Comment by rav-redchamps** [comment]
@refueledinc just for an update, we are able to figure out the problematic code and just evaluating a suitable code adjustment for it.

This code line is responsible for this behavior

https://github.com/redchamps/clean-admin-menu/blob/a19ece72c3f6c20b33cd90a0e1cfbe36326456bc/Plugin/Model/ConfigStructure.php#L55

if we replace it with code 

`$data = $subject->getData()`

and add below function to core file vendor/magento/module-config/Model/Config/Structure.php

```
public function getData()
{
     return $this->_data;
}
```

that will fix the problem. But obviously we can't change core file and rewriting it with preference will not work as well so just evaluating a suitable fix for it.

**Comment by thomas-kl1** [comment]
I'm working on this issue. I do have an idea.

Indeed `$data = $this->structureData->get(); ` is the issue.
The fix is removing that call and add an after plugin on `structureData->get()` and replace tab of sections that must be moved. At this moment we also can add an empty section for the title, as it done for the moment. So to summary we move the current logic to afterGet plugin, and we remove the current around one. I've tested locally and it works fine. I'll create the pull request tomorrow.

**Comment by rav-redchamps** [comment]
Hi @thomas-kl1 

Thank you for working on this issue.

The described solution makes sense. Here, the only thing to worry about is that the code `$data = $this->structureData->get();` is called in the constructor of class  `Magento\Config\Model\Config\Structure`

So if we put the logic under the after plugin of structureData->get() then the code will be called multiple times and might cause performance problems.

**Comment by thomas-kl1** [comment]
See fix https://github.com/redchamps/clean-admin-menu/blob/cacae7c794f44f0c928b53f0300d6ad58c597782/Model/Config/Structure/Data.php#L32

**Comment by rav-redchamps** [comment]
@refueledinc This has been fixed in recent release 1.0.3
