### ISSUE TITLE
get rid of "version" in composer.json

### ISSUE THREAD

**Issue by thomas-kl1** [redchamps/clean-admin-menu#7]
As we are using VCS for this package and tags, the "version" argument is not needed in the composer.json.
Removing it will be make easier to ship new releases without having to bump the version in composer.json each time.

**Comment by rav-redchamps** [comment]
@thomas-kl1 Thanks for the feedback. I can see 2 problems with this:

1. Packagist.org for composer installation, so not sure if it will work only with the tags
2. How an end-user will find out the installed version of the extension?

**Comment by thomas-kl1** [comment]
1. It works fine, composer, depending of the registered type (here vcs) know how to handle versions. A lot open-source project on github does not use "version" without any issue.
2. Normally the user set the version contraint in its project composer.json, anyway he can found it in composer.lock

**Comment by thomas-kl1** [comment]
The link I was searching about: https://getcomposer.org/doc/04-schema.md#version

**Comment by rav-redchamps** [comment]
Make sense. 

As you have already added this change to your pull request https://github.com/redchamps/clean-admin-menu/pull/6, I will mark this issue as closed once pull request is merged.
